[package]
name = "wgpu-experiments"
version = "0.1.0"
authors = ["Matus Talcik <matus.talcik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs" }
winit = "0.20.0-alpha5"
glsl-to-spirv = "0.1"
rand = "0.7"
zerocopy = "0.2"
rayon = "1.1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "sort"
harness = false